// Generated by CoffeeScript 1.3.3
(function() {
  var mainTab, mainWin, tabGroup;

  tabGroup = Titanium.UI.createTabGroup();

  mainWin = Titanium.UI.createWindow({
    title: "#appcelerator",
    backgroundColor: "#fff",
    url: "tweets.js",
    tabBarHidden: true
  });

  mainTab = Titanium.UI.createTab({
    title: "Twitter",
    icon: "KS_nav_mashup.png",
    window: mainWin
  });

  tabGroup.addTab(mainTab);

  tabGroup.open();

}).call(this);
